# Maven


trigger:
  - master

pool:
  vmImage: ubuntu-latest

steps:

- task: SonarCloudPrepare@3
  inputs:
    SonarCloud: 'lurodrig.sonarcloud.io'
    organization: 'luis-rodriguezfernandez-sonarsource'
    projectName: 'maven-basic'
    projectKey: 'luis-rodriguezfernandez-sonarsource_maven-basic'
    scannerMode: 'other'

- task: Maven@4
  inputs:
    mavenPomFile: 'pom.xml'
    mavenOptions: '-Xmx3072m'
    options: '-X'
    javaHomeOption: 'JDKVersion'
    jdkVersionOption: '1.17'
    jdkArchitectureOption: 'x64'
    publishJUnitResults: true
    testResultsFiles: '**/surefire-reports/TEST-*.xml'
    goals: 'clean verify sonar:sonar'

- task: SonarCloudPublish@3
  displayName: 'Code Analysis - Publish QG'
  inputs:
    pollingTimeoutSec: '300'