# Maven


trigger:
  - main

pool:
  vmImage: ubuntu-latest

steps:

- task: SonarQubePrepare@7
  inputs:
    SonarQube: 'SUPPORT-53337'
    scannerMode: 'other'
      
- task: Maven@4
  inputs:
    mavenPomFile: 'pom.xml'
    mavenOptions: '-Xmx3072m'
    options: '-X'
    javaHomeOption: 'JDKVersion'
    jdkVersionOption: '1.17'
    jdkArchitectureOption: 'x64'
    publishJUnitResults: true
    testResultsFiles: '**/surefire-reports/TEST-*.xml'
    goals: 'clean verify sonar:sonar'

- task: SonarQubePublish@7
  inputs:
    pollingTimeoutSec: '300'