# Maven


trigger:
- main

pool:
  vmImage: ubuntu-latest

steps:
- task: JavaToolInstaller@1
  inputs:
    versionSpec: '17'
    jdkArchitectureOption: 'x64'
    jdkSourceOption: 'PreInstalled'

- task: SonarQubePrepare@7
  inputs:
    SonarQube: 'lurodrig-sonarqube.ngrok.io'
    scannerMode: 'other'
    projectKey: maven-basic_maven-basic_bf4eb8fd-6ed8-40a3-9980-a1e66f86bb2e
    projectName: maven-basic
      
- task: Maven@4
  inputs:
    mavenPomFile: 'pom.xml'
    mavenOptions: '-Xmx3072m -X'
    javaHomeOption: 'JDKVersion'
    jdkVersionOption: '1.11'
    jdkArchitectureOption: 'x64'
    publishJUnitResults: true
    testResultsFiles: '**/surefire-reports/TEST-*.xml'
    goals: 'clean verify sonar:sonar'

- task: SonarQubePublish@7
  inputs:
    pollingTimeoutSec: '300'