# Maven


trigger:
  - master
  - develop
  - 62058_test_snowflake
  - feature/123456_test_snowflake

pool:
  vmImage: ubuntu-latest

steps:

- task: SonarCloudPrepare@3
  inputs:
    SonarCloud: 'lurodrig.sonarcloud.io'
    organization: 'luis-rodriguezfernandez-sonarsource'
    projectName: 'maven-basic'
    projectKey: 'luis-rodriguezfernandez-sonarsource_maven-basic'
    scannerMode: 'other'

- task: Maven@4
  inputs:
    mavenPomFile: 'pom.xml'
    mavenOptions: '-Xmx3072m'
    javaHomeOption: 'JDKVersion'
    jdkVersionOption: '1.17'
    jdkArchitectureOption: 'x64'
    publishJUnitResults: true
    testResultsFiles: '**/surefire-reports/TEST-*.xml'
    goals: 'clean verify sonar:sonar'
    options: '-X -Dsonar.projectKey=luis-rodriguezfernandez-sonarsource_maven-basic'

- task: SonarCloudPublish@3
  displayName: 'Code Analysis - Publish QG'
  inputs:
    pollingTimeoutSec: '300'